# Generated by Django 5.2.5 on 2025-08-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tasks.membershipplan'),
        ),
    ]
