# Generated by Django 5.2.5 on 2025-09-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_member_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
