# Generated by Django 5.2.5 on 2025-09-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, default='Member/default.png', null=True, upload_to='Member/'),
        ),
    ]
