# Generated by Django 5.2.5 on 2025-09-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='trainers',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='tasks.trainer'),
        ),
    ]
